name: haku_app
description: 示例flutter脚手架

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 生态自带图标集
  cupertino_icons: ^0.1.3
  # 查看程序包信息
  package_info: ^0.4.3
  # 生成Model
  json_annotation: ^3.1.1
  # 用于生成UUID
  uuid: ^2.2.2
  # 网络请求库
  dio: ^3.0.10
  # Dio的HTTP2请求库
  dio_http2_adapter: ^1.0.1
  # 用于查找文件系统上的常用位置
  path_provider: ^1.6.22
  # Get库
  get: ^3.13.2
  # 本地持久化库
  shared_preferences: ^0.5.12
  # 浮动弹出框（待定）
  oktoast: ^2.3.2
  # 图片缓存
  cached_network_image: ^2.3.3
  # 图片上传前压缩（待定）
  flutter_image_compress: ^0.7.0
  # 打印日志库
  logger: ^0.9.4
  # 本地日志库
  lite_log: ^0.1.4
  # 事件总线
  event_bus: ^1.1.1
  # 系统权限
  permission_handler: ^5.0.1
  # 微信SDK
  # fluwx: ^2.4.0
  # 为Protobuf的Dart实现提供运行时支持
  protobuf: ^1.1.0
  # 网络状态监控
  connectivity: ^2.0.1
  # 获取SIM系统信息
  flt_telephony_info: ^0.1.3
  # 用于启动URL
  url_launcher: ^5.7.3
  # [飞猪]万能组件
  fsuper: ^2.0.2
  # [飞猪]列表上拉下拉组件
  frefresh: ^1.1.0
  # 轮播
  flutter_swiper : ^1.1.6
  # 轮播附带页面指示器样式
  flutter_page_indicator: ^0.0.3
  # 轮播附带页面切换样式
  transformer_page_view: ^0.1.6


  # 通过不同的设备预览
  # device_preview: ^0.4.8
  # 震动
  # vibration: ^1.7.2
  # provider: ^4.3.2
  # 多图片选择器
  # multi_image_picker: ^4.7.14
  # 网页显示
  # webview_flutter: ^1.0.7
  # 系统分享
  # share_extend: ^1.1.9
  # 打开文件
  # open_file: ^3.0.3
  # 异常监控平台Sentry
  # sentry: ^3.0.1
  # 安卓OTA更新 (开发参考：https://www.jianshu.com/p/7029fe9a1d32)
  # ota_update: ^2.4.1
  # 谷歌tab栏
  # google_nav_bar: ^3.1.0
  # 导航栏
  # flashy_tab_bar: ^0.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # 
  build_runner: ^1.0.0
  # JSON格式化
  json_serializable: ^3.5.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/no-image.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Fryo
      fonts:
        - asset: assets/font/Fryo.ttf
  # - family: Schyler
  #   fonts:
  #     - asset: fonts/Schyler-Regular.ttf
  #     - asset: fonts/Schyler-Italic.ttf
  #       style: italic
  # - family: Trajan Pro
  #   fonts:
  #     - asset: fonts/TrajanPro.ttf
  #     - asset: fonts/TrajanPro_Bold.ttf
  #       weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
